development:
  adapter: postgresql
  encoding: utf-8
  database: test_task_dev_db
  host: localhost
  pool: 5
  username: mere_developer
  password: kinokino

test:
  adapter: postgresql
  encoding: utf-8
  database: test_task_test_db
  host: localhost
  pool: 5
  username: mere_developer
  password: kinokino

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
